### ISSUE TITLE
npm package is not the same version as source and returns an error

### ISSUE THREAD

**Issue by iamgeef** [kamranahmedse/aws-cost-cli#8]
Source is tagged with v0.2.5
Package is tagged with v0.2.4

When running the package (from `npm install -g aws-cost-cli`) I get a credential error: 

`InvalidClientTokenId: The security token included in the request is invalid`

Running `aws sts get-caller-identity` is successful, so my credentials are valid.

However, if I build from source and then run locally: 

`npm run build`
`node ./bin/index.js`

The tool works and I get my account costs.

I published a test package to npm using the latest source code and it worked, so seems to me the fix is to push the changes in v0.2.5 to npm.

**Comment by kamranahmedse** [comment]
Published, can you please try now
